### ISSUE TITLE
HTTP 500 on unhealthy system

### ISSUE THREAD

**Issue by cdelmas** [Nevon/express-physical#1]
It is possible to make the middleware return a HTTP 500 response when the system is unhealthy? That's the default behavior of many health checks libraries, and allows the monitoring systems to avoid parsing the response body.
It could be configurable (choose between 200 and 500).

**Comment by Nevon** [comment]
The purpose of this middleware is to allow monitoring systems to consume the response to take action intelligently. For example, correlate errors between dependent systems. If the monitoring system skips consuming the content, it will not be able to differentiate between a complete system failure and degraded functionality.

I don't like the idea of having this be configurable, because it means that the monitoring system has to deal with both 200 and 500 for failing healthchecks, since some systems will be configured to return 200 and some 500.

**Comment by Nevon** [comment]
I don't want to make this configurable, but it makes sense to return 500 if the healthchecks are failing.
